- name: Setup gcloud
  uses: google-github-actions/setup-gcloud@v2

- name: Install GKE auth plugin
  run: |
    gcloud components install gke-gcloud-auth-plugin --quiet

- name: Get GKE Credentials
  run: |
    gcloud container clusters get-credentials devops-cluster --zone asia-east1-b

- name: Deploy to Kubernetes
  run: |
    kubectl set image deployment/react-app react-app=asia-south1-docker.pkg.dev/devops-react-app/devops-repo/react-app:latest